### ISSUE TITLE
Change `XCTAssertEqualSequences` to report how the sequences are different

### ISSUE THREAD

**Issue by timvermeulen** [apple/swift-algorithms#100]
Our test suite contains the `XCTAssertEqualSequences` function which tests whether two sequences have equal elements, either based on `Equatable` conformance or using a custom predicate. It's currently implemented in terms of the `elementsEqual` method on `Sequence` which only returns whether or not the two sequences have equal elements.

For our purposes, when the two sequences are different, it would not only be useful to know _that_ they are different, but also _how_ they are different. Either the elements at the same position in the respective sequences aren't equal, or one of the sequences is shorter than the other one. `XCTAssertEqualSequences` should be changed to log this information to make debugging a bit easier.

**Comment by hashemi** [comment]
I'd love to work on it

**Comment by LucianoPAlmeida** [comment]
@timvermeulen PR was merged this can be closed :)
