### ISSUE TITLE
Convenience functions for `sum()` and `product()` across a `Collection` type

### ISSUE THREAD

**Issue by LemonSpike** [apple/swift-algorithms#108]
I regularly find myself wanting to sum all the (numeric) elements in a `Set`, `Array` or other `Collection`s. This made me think about whether adding a simple wrapper in the standard library for the sum and product operations, something along the lines of:

`collection.reduce(0,+)` for Sums
and
`collection.reduce(0,*)` for Products

(only for collections `where Element: Numeric`)

could be more clearer to write. In terms of implementation details, this is purely additive.

I don't know whether `reduce` would be the best way to implement this, but would be open to feedback on this. Might be a good starter issue?

**Comment by mdznr** [comment]
Wouldn’t `collection.reduce(0,*)` always produce 0 since 0 multiplied by anything is also 0?

It should be `collection.reduce(1, *)`. I think this would be one of the benefits of having a product convenience function, to avoid this kind of issue. There should probably also be consideration as to what the behavior is when the sequence length is 0. Is the output:
- 0?
- 1? This seems wrong, but is what `collection.reduce(1, *)` would produce without other checks.
- An error. You can’t get the product of no numbers.

**Comment by kylemacomber** [comment]
Thanks for proposing this @LemonSpike, the [conversation](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769) on the forums was really productive!

After talking with @stephentyrone, I think it makes the most sense for this functionality to live in [Swift Numerics](https://github.com/apple/swift-numerics), alongside other IEEE 754 reduction operations (as was discussed in the [forum thread](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769/11)).

**Comment by kylemacomber** [comment]
Thanks for proposing this @LemonSpike, the [conversation](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769) on the forums was really productive!

After talking with @stephentyrone, I think it makes the most sense for this functionality to live in [Swift Numerics](https://github.com/apple/swift-numerics), alongside other IEEE 754 reduction operations (as was discussed in the [forum thread](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769/11)).

**Comment by kylemacomber** [comment]
Thanks for proposing this @LemonSpike, the [conversation](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769) on the forums was really productive!

After talking with @stephentyrone, I think it makes the most sense for this functionality to live in [Swift Numerics](https://github.com/apple/swift-numerics), alongside other IEEE 754 reduction operations (as was discussed in the [forum thread](https://forums.swift.org/t/convenience-functions-for-sum-and-product-across-a-collection-type/45769/11)).

**Comment by kylemacomber** [comment]
@mdznr I think it being tricky or error-prone to choose an identity value for the reduce, is more of an argument for apple/swift-evolution#974.

**Comment by mdznr** [comment]
> apple/swift-evolution#974

I agree 🙂. That’ll allow the caller to determine what the correct behavior is.
