### ISSUE TITLE
Add GitHub workflow to run tests

### ISSUE THREAD

**Issue by MonicaG** [apple/swift-algorithms#122]
I would like to add a GitHub workflow to run the tests. I wanted to check-in first to see if this is wanted and if there are any requirements for it.

At a high level I would:
* on a push or pull request run the tests
* add a 'test' status badge to the README.md file

Are there any requirements for the machine and swift versions? Is it okay to run on 'macOS-latest' and use `swift test --enable-test-discovery` to run the tests? 

Thank you.

**Comment by natecook1000** [comment]
Hi @MonicaG! We're using the existing SwiftCI infrastructure for PR testing ([example](https://ci.swift.org/job/pr-swift-algorithms-linux/23/)), so we don't need to add any additional workflows here.
