### ISSUE TITLE
Publicize Collection.partitioningIndex(where:)

### ISSUE THREAD

**Issue by CTMacUser** [apple/swift-algorithms#131]
The `Collection.partitioningIndex(where:)` method is described in "Partition.md," the guide for its source file.  However, the master list on the library home-page's read-me does not list this method.  The read-me only lists the stable-partitioning methods in that same source file.  The `partitioningIndex` method should be listed in the read-me file.  It needs to be in a different category, though.

**Comment by LemonSpike** [comment]
Happy to take this one! Can you share a summary of what things might be good to include (any differences to the guide)?

**Comment by LemonSpike** [comment]
This can be closed now.
