### ISSUE TITLE
Using GitHub Bots?

### ISSUE THREAD

**Issue by LemonSpike** [apple/swift-algorithms#135]
GitHub has lots of really handy bots that integrate with pushed commits and PR actions, as well as GitHub Actions CI. I have used GitHub’s bots in my own projects and found them very secure, helpful and easy to integrate.

I have raised #133 re: [ImgBot] but I am open to your feedback on more general Bot integrations as well.

Thanks.

**Comment by natecook1000** [comment]
We're just sticking with Swift CI for now. Thanks, @LemonSpike!
