### ISSUE TITLE
Consider using @discardableResult where possible. 

### ISSUE THREAD

**Issue by kennycarruthers** [apple/swift-algorithms#187]
Some of the algorithms in this package have a return value that might not be needed by the caller. It would be nice if these were marked as `@ discardableResult` so that callers don't have to use `_ =` to silence Xcode warnings. 

For example, `stablePartition` returns the start of the resulting suffix, which might not be of interest to a caller who's only interested in the final result.

**Comment by mdznr** [comment]
https://github.com/apple/swift-algorithms/issues/67

**Comment by kennycarruthers** [comment]
Oops, sorry. Not sure how I missed that obvious duplicate! Feel free to close this issue.
