### ISSUE TITLE
Documentation -- How to use on linux

### ISSUE THREAD

**Issue by igouy** [apple/swift-algorithms#244]
I've downloaded and unpacked: `swift-algorithms-1.2.0`

I've figured out how to do:

```
/opt/src/swift-algorithms-1.2.0$ /opt/src/swift-6.0-RELEASE/usr/bin/swift build -c release
warning: 'swift-algorithms-1.2.0': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /opt/src/swift-algorithms-1.2.0/Sources/Algorithms/Documentation.docc
Building for production...
[1/1] Write swift-version-4F43B41217B24F1D.txt
Build complete! (1.37s)
```

I've added `swift-algorithms-1.2.0` to  PATH and inserted `import Algorithms` into the source file.

But

```
 1 | import Algorithms
   |        `- error: no such module 'Algorithms'
```

**Comment by xwu** [comment]
Swift Algorithms is a package. You'll want to use Swift Package Manager in order to add it as a dependency to your project.  
For more on using Swift Package Manager, you can start with this link: https://www.swift.org/documentation/package-manager/

**Comment by igouy** [comment]
Thanks for the prompt helpful reply. 

> You don't need to manually 

I would prefer to say where and what SwiftPM installs.

**Comment by xwu** [comment]
I am not aware of any straightforward way to make that work; however, others might have some ideas.
