### ISSUE TITLE
Add a suffix(while:) method

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-algorithms#62]
The standard library includes `prefix` and `suffix` methods that take a number of elements or an index, but only a `prefix` method that takes a predicate. We should add a `suffix(while:)` method to match `prefix(while:)` for bidirectional collections.

**Comment by michiboo** [comment]
Hi I would like to take this issue!  where should I add suffix(while:) methods?

**Comment by kylemacomber** [comment]
Please open a PR against this package. It probably makes sense to add a new file, say `Sources/Algorithms/Suffix.swift`, and add your implementation there.
