### ISSUE TITLE
striding(by:) sometimes slower than expected

### ISSUE THREAD

**Issue by timvermeulen** [apple/swift-algorithms#63]
This code should be fast, but isn't:

```swift
for x in (0..<10_000_000).striding(by: 1_000_000) {
  // ...
}
```

`Stride`'s iterator wraps the base collection's iterator, and can't skip over multiple elements at a time. By forcing the iterator to be an `IndexingIterator`, the code is fast again:

```swift
for x in (0..<10_000_000).striding(by: 1_000_000)[...] {
  // ...
}
```

I don't think we can vary the `Stride.Iterator` associated type based on whether `Base` conforms to `Collection`, so the only way to fix this that I can think of is to split up `Stride` into two types (with two overloads), one for sequences and one for collections.

**Comment by ollieatkinson** [comment]
Thanks very much for raising this @timvermeulen - this is certainly not the performance one would expect when using this sequence. Nice catch 🎣 !

As you mention - we can implement the improved algorithm by abstracting away the iterator into it's own type to allow for the optimisation to apply in the case where `Base` is `Collection`.

```swift
extension Sequence {
    public func striding(by step: Int) -> StrideSequence<Self> {
        StrideSequence(base: self, stride: step)
    }
}

extension Collection {
    public func striding(by step: Int) -> Stride<Self> {
        Stride(base: self, stride: step)
    }
}

public struct StrideSequence<Base: Sequence>: Sequence {
    
    let base: Base
    let stride: Int
    
    init(base: Base, stride: Int) {
        precondition(stride > 0, "striding must be greater than zero")
        self.base = base
        self.stride = stride
    }
}

extension StrideSequence {
    
    public struct Iterator: IteratorProtocol {
        
        var iterator: Base.Iterator
        let stride: Int
        var striding: Bool = false
        
        public mutating func next() -> Base.Element? {
            guard striding else {
                striding = true
                return iterator.next()
            }
            for _ in 0..<stride - 1 {
                guard iterator.next() != nil else { break }
            }
            return iterator.next()
        }
    }
    
    public func makeIterator() -> StrideSequence<Base>.Iterator {
        Iterator(iterator: base.makeIterator(), stride: stride)
    }
}
```

**Comment by ollieatkinson** [comment]
I had a go at implementing this change (https://github.com/ollieatkinson/swift-algorithms/commit/70fead57605292a3d0b9160f1079f304a0573e25) but I'm unsure how best to validate the improvement.

When running similar examples to the one you gave with `measure` I get the following results:
```swift
  func testMeasureSequence() {
    measure {
      for _ in (0..<100_000_000).striding(by: 1_000) { }
    }
  }
  
  func testMeasureCollection() {
    measure {
      for _ in (0..<100_000_000).striding(by: 1_000)[...] { }
    }
  }
```
  
![image](https://user-images.githubusercontent.com/1382565/110172632-54e9cc80-7df5-11eb-9b23-052a1d9b28ff.png)
![image](https://user-images.githubusercontent.com/1382565/110172703-721e9b00-7df5-11eb-8c45-c01dac090caa.png)

↑ This is the opposite to what I would expect

**Comment by natecook1000** [comment]
Both of those look like they're using the collection version. You can opt into the sequence like this: `let s: StrideSequence = (0..<100_000_000).striding(by: 1_000)`

**Comment by ollieatkinson** [comment]
Of course! Thanks, I've raised the P/R - I didn't commit the performance tests as I was unsure since there was no other examples of this being done.
