### ISSUE TITLE
.combinations(ofCount k:) not working 

### ISSUE THREAD

**Issue by LemonSpike** [apple/swift-algorithms#72]
`combinations(ofCount:)` not working in a command line app for the documented examples.

**Swift Algorithms version:** `0.0.2`
**Swift version:** 5 (selected from build settings).

### Checklist
- [X] If possible, I've reproduced the issue using the `main` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-algorithms/issues)

### Steps to Reproduce
Created a new command-line app with v 0.0.2 of the Algorithms Swift Package, successfully compiled. I am trying to use `combinations(ofCount: )` but it doesn't seem to work. I've tried with String and Int arrays, but the result of the combo only includes the original array. I've pretty much followed the documentation word-for-word, with the example.

```
func algorithmCombinations(_ digits: [Int]) -> [Int] {
  let combos = digits.combinations(ofCount:3)
  var results = [Int]()
  for combo in combos {
    results.append(contentsOf: combo)
    print(combo)
  }
  return results
}

let res = algorithmCombinations([3,6,2]) // prints [3,6,2]
```

### Expected behavior
Describe what you expect to happen.

`[2,3,6],[2,6,3],[3,2,6],[3,6,2],[6,2,3],[6,3,2]` gets printed and returned.

### Actual behavior
Describe or copy/paste the behavior you observe.
`let res = algorithmCombinations([3,6,2]) // prints and returns [3,6,2]`

**Comment by timvermeulen** [comment]
> ### Expected behavior
> Describe what you expect to happen.
> 
> `[2,3,6],[2,6,3],[3,2,6],[3,6,2],[6,2,3],[6,3,2]` gets printed and returned.

It sounds like you're looking for the `permutations(ofCount:)` method 🙂 In a permutation the order matters, in a combination it does not. `[2, 3, 6]` and `[2, 6, 3]` are the same combination of 3 elements, just in a different order.

**Comment by LemonSpike** [comment]
Ok, I understand now. Thanks for the help.
