### ISSUE TITLE
Prepare for 0.0.3 release

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-algorithms#80]
Here's a checklist of the remaining work to do for the next `Algorithms` release:

- [x] Add guides for `suffix(while:)` and any other new methods: #82
- [x] Rename `sortedPrefix`: #77
- [x] Rename `slidingWindows`: #79
- [x] Audit inlinability annotations throughout: #83
- [x] Verify that all methods are called out in the README
- [x] Update the CHANGELOG

**Comment by dhruvshah8** [comment]
I have made a Guide for the Suffix(while:) function. How should I add it?

**Comment by natecook1000** [comment]
Thanks, @dhruvshah8! Pull requests are welcome - are you familiar with that process?

**Comment by dhruvshah8** [comment]
No not really, how do I do so?

**Comment by natecook1000** [comment]
You should be able to do this all through GitHub! Go to the Guides directory and click the "Create New File" link (it might be hiding under a `...` button). Once you've added the content of your guide, at the bottom of the page you should see a "Commit new file" section. Add a commit message there (something like "Add a guide for suffix(while:)") and choose the option that will create a branch and start a pull request.

Happy to help more if you run into any issues!

**Comment by natecook1000** [comment]
All set!
